export const Configuration: typeof import("./configuration");
export const Record: {
    Fields: {
        BooleanCustomFieldRef: typeof import("./record/fields/booleanCustomFieldRef");
        BooleanRef: typeof import("./record/fields/booleanRef");
        DoubleRef: typeof import("./record/fields/doubleRef");
        FloatRef: typeof import("./record/fields/floatRef");
        RecordRef: typeof import("./record/fields/recordRef");
        SelectCustomFieldRef: typeof import("./record/fields/selectCustomFieldRef");
        StringCustomFieldRef: typeof import("./record/fields/stringCustomFieldRef");
        DoubleCustomFieldRef: typeof import("./record/fields/doubleCustomFieldRef");
        StringRef: typeof import("./record/fields/stringRef");
    };
    Lists: {
        Address: typeof import("./record/lists/address");
        CustomerAddressbook: typeof import("./record/lists/customerAddressbook");
        CustomerAddressbookList: typeof import("./record/lists/customerAddressbookList");
        CustomFieldList: typeof import("./record/lists/customFieldList");
        NullFieldList: typeof import("./record/lists/nullFieldList");
        SalesOrderItem: typeof import("./record/lists/salesOrderItem");
        SalesOrderItemList: typeof import("./record/lists/salesOrderItemList");
    };
    Types: {
        BillingAccount: typeof import("./record/types/billingAccount");
        CashSale: typeof import("./record/types/cashSale");
        Contact: typeof import("./record/types/contact");
        Customer: typeof import("./record/types/customer");
        CustomerStatus: typeof import("./record/types/customerStatus");
        CustomRecord: typeof import("./record/types/customRecord");
        CustomRecordRef: typeof import("./record/types/customRecordRef");
        EntityGroup: typeof import("./record/types/entityGroup");
        Estimate: typeof import("./record/types/estimate");
        Invoice: typeof import("./record/types/invoice");
        ItemFulfillment: typeof import("./record/types/itemFulfillment");
        ListOrRecordRef: typeof import("./record/types/listOrRecordRef");
        Opportunity: typeof import("./record/types/opportunity");
        Partner: typeof import("./record/types/partner");
        RecordRef: typeof import("./record/types/recordRef");
        SalesOrder: typeof import("./record/types/salesOrder");
        Vendor: typeof import("./record/types/vendor");
    };
};
export const Search: {
    Advanced: {
        CashSaleSearchAdvanced: typeof import("./search/Advanced/cashSaleSearchAdvanced");
        CashSaleSearchRow: typeof import("./search/Advanced/cashSaleSearchRow");
        CashSaleSearchRowBasic: typeof import("./search/Advanced/cashSaleSearchRowBasic");
        CustomerSearchAdvanced: typeof import("./search/Advanced/customerSearchAdvanced");
        CustomerSearchRow: typeof import("./search/Advanced/customerSearchRow");
        CustomerSearchRowBasic: typeof import("./search/Advanced/customerSearchRowBasic");
        InvoiceSearchAdvanced: typeof import("./search/Advanced/invoiceSearchAdvanced");
        InvoiceSearchRow: typeof import("./search/Advanced/invoiceSearchRow");
        InvoiceSearchRowBasic: typeof import("./search/Advanced/invoiceSearchRowBasic");
        ItemFulfillmentSearchAdvanced: typeof import("./search/Advanced/itemFulfillmentSearchAdvanced");
        ItemFulfillmentSearchRow: typeof import("./search/Advanced/itemFulfillmentSearchRow");
        ItemFulfillmentSearchRowBasic: typeof import("./search/Advanced/itemFulfillmentSearchRowBasic");
        ItemSearchAdvanced: typeof import("./search/Advanced/itemSearchAdvanced");
        ItemSearchRow: typeof import("./search/Advanced/itemSearchRow");
        ItemSearchRowBasic: typeof import("./search/Advanced/itemSearchRowBasic");
        LocationSearchAdvanced: typeof import("./search/Advanced/locationSearchAdvanced");
        LocationSearchRow: typeof import("./search/Advanced/locationSearchRow");
        LocationSearchRowBasic: typeof import("./search/Advanced/locationSearchRowBasic");
        SalesOrderSearchAdvanced: typeof import("./search/Advanced/salesOrderSearchAdvanced");
        SalesOrderSearchRow: typeof import("./search/Advanced/salesOrderSearchRow");
        SalesOrderSearchRowBasic: typeof import("./search/Advanced/salesOrderSearchRowBasic");
        SubsidiarySearchAdvanced: typeof import("./search/Advanced/subsidiarySearchAdvanced");
        SubsidiarySearchRow: typeof import("./search/Advanced/subsidiarySearchRow");
        SubsidiarySearchRowBasic: typeof import("./search/Advanced/subsidiarySearchRowBasic");
    };
    Basic: {
        CashSaleSearchBasic: typeof import("./search/Basic/cashSaleSearchBasic");
        CustomerSearchBasic: typeof import("./search/Basic/customerSearchBasic");
        InvoiceSearchBasic: typeof import("./search/Basic/invoiceSearchBasic");
        ItemFulfillmentSearchBasic: typeof import("./search/Basic/itemFulfillmentSearchBasic");
        ItemSearchBasic: typeof import("./search/Basic/itemSearchBasic");
        LocationSearchBasic: typeof import("./search/Basic/locationSearchBasic");
        SalesOrderSearchBasic: typeof import("./search/Basic/salesOrderSearchBasic");
        SubsidiarySearchBasic: typeof import("./search/Basic/subsidiarySearchBasic");
    };
    Fields: {
        SearchBooleanField: typeof import("./search/Fields/searchBooleanField");
        SearchColumnBooleanCustomField: typeof import("./search/Fields/searchColumnBooleanCustomField");
        SearchColumnBooleanField: typeof import("./search/Fields/searchColumnBooleanField");
        SearchColumnCustomField: typeof import("./search/Fields/searchColumnCustomField");
        SearchColumnCustomFieldList: typeof import("./search/Fields/searchColumnCustomFieldList");
        SearchColumnDateCustomField: typeof import("./search/Fields/searchColumnDateCustomField");
        SearchColumnDateField: typeof import("./search/Fields/searchColumnDateField");
        SearchColumnDoubleCustomField: typeof import("./search/Fields/searchColumnDoubleCustomField");
        SearchColumnDoubleField: typeof import("./search/Fields/searchColumnDoubleField");
        SearchColumnEnumMultiSelectCustomField: typeof import("./search/Fields/searchColumnEnumMultiSelectCustomField");
        SearchColumnEnumSelectField: typeof import("./search/Fields/searchColumnEnumSelectField");
        SearchColumnLongCustomField: typeof import("./search/Fields/searchColumnLongCustomField");
        SearchColumnLongField: typeof import("./search/Fields/searchColumnLongField");
        SearchColumnMultiSelectCustomField: typeof import("./search/Fields/searchColumnMultiSelectCustomField");
        SearchColumnSelectCustomField: typeof import("./search/Fields/searchColumnSelectCustomField");
        SearchColumnSelectField: typeof import("./search/Fields/searchColumnSelectField");
        SearchColumnStringCustomField: typeof import("./search/Fields/searchColumnStringCustomField");
        SearchColumnStringField: typeof import("./search/Fields/searchColumnStringField");
        SearchColumnTextNumberField: typeof import("./search/Fields/searchColumnTextNumberField");
        SearchDateField: typeof import("./search/Fields/searchDateField");
        SearchDoubleField: typeof import("./search/Fields/searchDoubleField");
        SearchEnumMultiSelectField: typeof import("./search/Fields/searchEnumMultiSelectField");
        SearchLongField: typeof import("./search/Fields/searchLongField");
        SearchMultiSelectField: typeof import("./search/Fields/searchMultiSelectField");
        SearchStringField: typeof import("./search/Fields/searchStringField");
        SearchTextNumberField: typeof import("./search/Fields/searchTextNumberField");
    };
    SearchPreferences: typeof import("./search/searchPreferences");
};
export const Service: typeof import("./service");
export const Soap: {
    RequestPreferences: typeof import("./soap/requestPreferences");
};
export const Util: typeof import("./util");
