export const BooleanCustomFieldRef: typeof import("./booleanCustomFieldRef");
export const BooleanRef: typeof import("./booleanRef");
export const DoubleRef: typeof import("./doubleRef");
export const FloatRef: typeof import("./floatRef");
export const RecordRef: typeof import("./recordRef");
export const SelectCustomFieldRef: typeof import("./selectCustomFieldRef");
export const StringCustomFieldRef: typeof import("./stringCustomFieldRef");
export const DoubleCustomFieldRef: typeof import("./doubleCustomFieldRef");
export const StringRef: typeof import("./stringRef");
